---
kind: pipeline
type: ssh
name: deploy

server:
    host:
      from_secret: host
    user:
      from_secret: username
    ssh_key:
      from_secret: ssh_key

clone:
    disable: true

trigger:
    branch:
      - master

steps:
    - name: deploy
      commands:
        - ssh root@ff-www "/usr/local/bin/ffdd-page-update.sh"
